### ISSUE TITLE
Extract utils for uniform parallel code to own package

### ISSUE THREAD

**Issue by SteffenPL** [omlins/ParallelStencil.jl#160]
I quite like the design of this package and often need some of the parts, like `@zeros`, `Data.Array` in other projects which per-se do not require the other features of ParallelStencil.jl.

Would it be possible/welcome to extract those bits into a own package? E.g. a package which is just there to load the right backend and have uniform names for common operations, for example for using with KernelAbstractions.jl

Anyway, feel free to close as it is not really an "issue" ;)

**Comment by omlins** [comment]
> I quite like the design of this package and often need some of the parts, like @zeros, Data.Array in other projects which per-se do not require the other features of ParallelStencil.jl.
Thanks for sharing this and for your interest!

It is not so clear to me and though what you would consider extracting into a separate package. Would that be essentially everything that is not stencil specific? All that is since the beginning kept in a submodule [ParallelStencil.ParallelKernel](https://github.com/omlins/ParallelStencil.jl/tree/main/src/ParallelKernel), which indeed could at some point fairly easy become an independent package.

Also, to do a backend that generates KernelAbstractions code is planned.

Finally, all backend-related packages have become weak dependencies and are used via extensions. Thus, the base package is rather lightweight if that is your concern.

**Comment by SteffenPL** [comment]
Thanks for the quick reply! 

I really should have looked at the code first, `ParallelStencil.ParallelKernel` is precisely what I was looking for. Indeed, `ParallelStencil.jl` is not too heavy in terms of non-weak dependencies!
