### ISSUE TITLE
Spatially varying parameters?

### ISSUE THREAD

**Issue by ziyiyin97** [omlins/ParallelStencil.jl#4]
Hi Ludovic and Samuel,

Hope you stepped into the new year with ease. I have experienced with your julia software in a while, thanks to your clear documentation and workflow!

I have a couple of questions about https://github.com/omlins/ParallelStencil.jl/blob/main/miniapps/HydroMech2D.jl
while I am using the software:

1. How do we allow the background porosity distribution to be spatially varying? Right now the background porosity is set to be homogenous as <img src="https://render.githubusercontent.com/render/math?math=\phi_0"> and only accepts scalar (since other physical parameters also depend on it, e.g. time step). Same for density, etc.
2. When simulating with larger background porosity (e.g. 0.2) and larger perturbation (e.g. 0.4), the behavior does not look like chimneys but more like "blobs". Is this behavior expected? Also, do I have to change the physical time stepping and reduction time stepping accordingly?

Thanks a lot for your help!

Kind Regards,

Francis

**Comment by ziyiyin97** [comment]
Also, will the adjoint-based inversion solver be available in this ParallelStencil.jl package in the future?

**Comment by omlins** [comment]
Hi Francis,

I hope you had a good start into the new year too. We are happy to hear that you are enjoying to work with ParallelStencil!

The fact that this package is only since a short time publicly available requires us to solve still a few organizational issues; one of them you have just brought up: where should we discuss numerical/domain-science issues in order to keep them separate from technical issues with the package and have them optimally visible to the Julia community? I have just discussed with Ludovic and we believe the right place is Julia discourse. Thus, would you mind to help us to get these kind of discussions grow at the right place by posting the above questions on Julia Discourse in the [Numerics topic](https://discourse.julialang.org/c/domain/numerics/) or the [Modelling & Simulations topic](https://discourse.julialang.org/c/domain/models)? I just noted this in the section [Questions, comments and discussions](https://github.com/omlins/ParallelStencil.jl#questions-comments-and-discussions) :) .

Thanks a lot! Ludovic will reply to your questions tomorrow...

Cheers,

Sam

**Comment by ziyiyin97** [comment]
Sure! The question is posted here https://discourse.julialang.org/t/numerical-questions-about-spatially-varying-parameters-for-parallelstencil-jl/53558?u=ziyiyin97

**Comment by omlins** [comment]
Thanks @ziyiyin97 !
