### ISSUE TITLE
Can I use this package to solve linear equation A*x=b in GPU? If can, please give me some instructions. Thank you very much.

### ISSUE THREAD

**Issue by liaoweiyang2017** [omlins/ParallelStencil.jl#40]

**Comment by luraess** [comment]
Hi @liaoweiyang2017, thank you for your interest in ParallelStencil. The short answer is yes - considering an iterative approach.

Since your question is not an issue with the package but rather an application / usage question, could you please re-post it on Julia Discourse in the most appropriate section [as suggested here](https://github.com/omlins/ParallelStencil.jl#questions-comments-and-discussions) - maybe in [Modelling & Simulations](https://discourse.julialang.org/c/domain/models) topic ? As such, other folks can also enjoy the discussion.

I can provide further help on Discourse.
